#user container-based infrastructure
os: linux
sudo: required
addons:
  chrome: stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.7.1/bin/
  - export CHROME_BIN=chromium-browser

# install dependencies
#install: "pip install -r requirements.txt"
install:
  - make deps
language: python
python:
  - "3.7"
script:
  - python -m unittest lost_hat_tests.LostHatTests
  - google-chrome --version