#user container-based infrastructure
os: linux
sudo: required
addons:
  chrome: stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.7.1/lib/python3.7/bin/
  - export CHROME_BIN=chromium-browser

# install dependencies
#install: "pip install -r requirements.txt"
install:
  - make deps
language: python
python:
  - "3.7"
script:
  - make test
  - google-chrome --version